### ISSUE TITLE
Crash on start up, using native launcher and Rift ver 1.0.4-86

### ISSUE THREAD

**Issue by dicedicediceaf1** [Burgersim/PGEG#28]
16:24:58 | launcher | Preparing to launch minecraft client for 1.13-rift-1.0.4-86
-- | -- | --
16:24:58 | launcher | Couldn't get hash for org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar from https://www.dimdev.org/maven/org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar.sha1: HTTP 404: Not Found
16:24:58 | launcher | Have local file C:/Users\Aeronautic\AppData\Roaming\.minecraft\libraries\org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar but don't know what size or hash it should be. Have to assume it's good.
16:24:59 | launcher | Checking installations.
16:24:59 | launcher | Minecraft client 1.13-rift-1.0.4-86 is ready to start.
16:24:59 | launcher | Starting!
16:25:00 | launcher | Using default game log configuration client-1.12.xml (outputs XML)
16:25:01 | LaunchWrapper | Loading tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
16:25:01 | LaunchWrapper | Using primary tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
16:25:01 | LaunchWrapper | Calling tweak class org.dimdev.riftloader.launch.RiftLoaderClientTweaker
16:25:01 | RiftLoader | Searching mods on classpath
16:25:01 | RiftLoader | Loaded mod 'rift'
16:25:01 | RiftLoader | Searching for mods in C:\Users\Aeronautic\AppData\Roaming\.minecraft\mods
16:25:01 | RiftLoader | Loaded mod 'almostenoughitems'
16:25:01 | RiftLoader | Loaded mod 'pgeg'
16:25:01 | RiftLoader | Loaded 3 mods
16:25:01 | RiftLoader | Initializing mods
16:25:01 | LaunchWrapper | Unable to launch java.lang.RuntimeException: java.lang.reflect.InvocationTargetException at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:28) at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.reflect.InvocationTargetException at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at org.dimdev.riftloader.launch.RiftLoaderTweaker.injectIntoClassLoader(RiftLoaderTweaker.java:26) ... 2 more Caused by: java.lang.RuntimeException: Failed to find listener class org.burgersim.pgeg.listener.PgegPotions at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:181) at org.dimdev.riftloader.RiftLoader.load(RiftLoader.java:54) ... 7 more Caused by: java.lang.ClassNotFoundException: org.burgersim.pgeg.listener.PgegPotions at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) at org.dimdev.riftloader.RiftLoader.initMods(RiftLoader.java:178) ... 8 more Caused by: java.lang.NoClassDefFoundError: com/github/ondee/snowflake/listener/PotionAdder at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(ClassLoader.java:760) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ... 9 more Caused by: java.lang.ClassNotFoundException: com.github.ondee.snowflake.listener.PotionAdder at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ... 13 more Caused by: java.lang.NullPointerException at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ... 15 more
16:25:01 | launcher |  
11:25:01 | monitor | Process crashed with exit code 1

**Comment by vladyslav-vasiliev** [comment]
Install snowflake lib https://minecraft.curseforge.com/projects/snowflake
